### ISSUE TITLE
Plugin not closing down VSCode problems when APIs are closed

### ISSUE THREAD

**Issue by savage-alex** [SmartBear/vscode-swaggerhub-release#7]
When I close an API definition, its normal for any problems that are registered against the opened file to be purged in VS Code.

This does not happen with the current version of the plugin.
![image](https://user-images.githubusercontent.com/25430683/98944974-c79f0700-24e9-11eb-8b1b-5070897e9e77.png)

Workaround is to close VSCode and re-open it.

To get some problems, suggest installing https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker and introducing spelling mistakes in a definition. On close the terminal errors remain and if you open another definition they are still there confusing the editor.

**Comment by tmaguiresmartbear** [comment]
Hi @savage-alex 
We dug into this issue and found that the problem is located inside the redhat yaml editor that we inherit to assist with the yaml editing.  We are looking for a workaround, however it appears to be an open problem in VS Code for years: https://github.com/microsoft/vscode/issues/66982
